version: "3.8"

services:
  backend:
    volumes:
      - ./AdBoard/backend:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development

  # Add any other development-specific overrides here
